name: Deploy in K8S

on:
  pull_request:
    branches: [main]

jobs:
  build:
     runs-on: ubuntu-latest
     env:
        DOCKER_IMAGE_NAME: tor-gateway
        DOCKER_TAG: 0.${{ github.run_number }}
        DEPLOY_YAML: yamls/tor-gateway-deploy-template.yaml
     steps:
     - name: Checkout
       uses: actions/checkout@v3
       
     - name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKER_TOKEN }}
    
     - name: Build Docker Image
       run:  docker build . -t ${{ secrets.DOCKER_USER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }} -f Dockerfile
       
     - name: Push Docker Image to DockerHub
       run : docker push ${{ secrets.DOCKER_USER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}
       
     - name: Set K8S Config
       run: mkdir ~/.kube && echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
      
     - name: Change Image Name In Yaml
       run: sed -i 's/#VERSION_STRING#/${{ secrets.DOCKER_USER }}\/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}/g' ${{ env.DEPLOY_YAML }} 
      
     - name: Deploy on K8S
       run: kubectl apply -f ${{ env.DEPLOY_YAML }}
